spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password:
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      # nunca Subir com create-drop
      ddl-auto: create-drop
    generate-ddl: true



